runtime: go111

instance_class: F1

handlers:
- url: /api/post
  script: auto
  secure: always

- url: /api/list
  script: auto
  secure: always

- url: /api/picture
  script: auto
  secure: always

- url: /api/delete
  script: auto
  secure: always

- url: /p/.*
  script: auto
  secure: always

- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|json|svg))$
  static_files: web/build/\1
  upload: web/build/(.*)
  secure: always

- url: /(.*)
  static_files: web/build/index.html
  upload: web/build/index.html
  secure: always
